version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: make test

      - save_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
